---
# middleware/roles/db2/tasks/main/install.yml
# @version v1.03_2025-MAR-18
# @author Kevin Jeffery

- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ db2_packages }}"
    state: latest
  become: yes
  tags: always

- name: Disabling SELinux
  lineinfile:
    path: /etc/selinux/config
    line: SELINUX=disabled
    regex: ^SELINUX=
  become: yes 
  notify: Reboot server
  tags: always

- meta: flush_handlers
  tags: always

- name: Add entry to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ip_address }}.*{{ host_name }}"
    line: "{{ ip_address }} {{ host_name }} {{ host_name.split('.') | first }}"
  become: yes
  tags: always

- name: Unarchive Software
  ansible.builtin.unarchive:
    src: "{{ db2_source_dir }}/{{ item.archive }}"
    dest: "{{ db2_source_dir }}"
    creates: "{{ db2_source_dir }}/{{ item.creates }}"
    remote_src: yes
  loop:
    - archive: "{{ db2_info.archive }}"
      creates: "{{ db2_info.creates }}"
    - archive: "{{ db2_info.db2_license_archive | default('') }}"
      creates: "{{ db2_info.db2_license_file | default('') }}"
    - archive: "{{ db2_info.db2_highcapacity_archive | default('') }}"
      creates: "{{ db2_info.db2_highcapacity_file | default('') }}"
  loop_control:
    label: "{{ item.archive }}"
  when: item.archive is defined
  tags: always

- name: Run DB2 Pre-Requisite Check
  ansible.builtin.command: "{{ software_dest_dir }}/{{ db2_info.creates }}/db2prereqcheck -i -s"
  register: precheck
  failed_when:
  - "'mksh' not in precheck.stderr" # Fix for https://www.ibm.com/support/pages/db2prereqcheck-returns-dbt3507e-due-missing-mksh-or-psmisc-packages
  - "'failed' in precheck.stderr"
  changed_when: False
  become: yes
  tags: always

- name: Template response file
  ansible.builtin.template: 
    src: db2server.rsp.j2
    dest: "{{ software_dest_dir }}/db2server.rsp"
  tags: always

- name: Installing DB2
  ansible.builtin.command: "{{ software_dest_dir }}/{{ db2_info[db2_version][db2_edition].creates }}/db2setup -f sysreq -r {{ software_dest_dir }}/db2server.rsp"
  register: db2_setup
  args: 
    creates: "{{ db2_home }}"
  become: yes
  notify:
  - Sync GSKit32
  - Sync GSKit64
  - Sync JavaSDK
  - Reboot server
  tags: always

- name: Setup results
  ansible.builtin.debug: 
    var: db2_setup.stdout_lines
  tags: always

- name: Validating the current installation
  autom8.middleware.db2license:
    action: version
    db2_home: "{{ db2_home }}"
  register: ret_db2_version
  failed_when:  not ret_db2_version.data.installed
  tags: always

- name: Deploy DB2 Fault Monitor Coordinator Daemon Service file
  ansible.builtin.template:
    src: db2fmcd.service.j2
    dest: /etc/systemd/system/db2fmcd.service
    force: yes
  become: yes
  notify: Enable DB2 Service
  tags: always
