---
# middleware/roles/gskit/vars/main.yml
# @version v2025.2.13.0
# @author Kevin Jeffery

gskit_info:
  "8.0.55.9":
    archive: 8.0.55.9-ISS-GSKIT-LinuxX64-FP009.tar.gz
    name: 8.0.55.9-ISS-GSKIT-LinuxX64-FP009
  "8.0.55.26":
    archive: 8.0.55.26-ISS-GSKIT-LinuxX64-FP0026.tar.gz
    name: 8.0.55.26-ISS-GSKIT-LinuxX64-FP0026
  "8.0.55.31":
    archive: 8.0.55.31-ISS-GSKIT-LinuxX64-FP0031.tar.gz
    name: 8.0.55.31-ISS-GSKIT-LinuxX64-FP0031
