---
namespace: autom8
name: isamva
version: 2025.2.9
readme: README.md
authors:
- Kevin Jeffery <kevin@microknight.com>
description: Bespoke roles and modules for IBM Security Verify Access Installation and Management
license:
- Apache-2.0
tags:
- ISVA
dependencies: {}
repository: https://github.com/kjeffery14/autom8
# documentation:
# homepage:
# issues:
