---
# isamva/roles/rtss/tasks/scim_configuration.yml
# @version v1.04_2023-OCT-27
# @author Kevin Jeffery

- block:
  - name: SCIM General Settings
    ibm.isam.isam:
      action: ibmsecurity.isam.aac.scim.general.set
      isamapi:
        enable_header_authentication: "{{ rtss_scim_config.general.enable_header_authentication | default(omit) }}"
        enable_authz_filter: "{{ rtss_scim_config.general.enable_authz_filter | default(omit) }}"
        admin_group: "{{  }}"
  - name: SCIM ISAM User Configuration
    ibm.isam.isam:
      action: ibmsecurity.isam.aac.scim.update_isam_user
      isamapi:
        isam_domain: "{{ rtss_scim_config.isam_user.isam_domain | default('Default') }}"
        ldap_connection: "{{ rtss_scim_config.isam_user.ldap_connection }}"
        update_native_users: "{{ rtss_scim_config.isam_user.update_native_users | default('false') }}"
    register: ret_out
    when:
      - rtss_scim_config.isam_user is defined
      - rtss_scim_config.isam_user.ldap_connection is defined
    notify:
    - Commit Changes
 
  - name: SCIM User Profile Configuration
    ibm.isam.isam:
      action: ibmsecurity.isam.aac.scim.user_profile.set
      isamapi:
        connection_type: ldap
        enforce_password_policy: "{{ rtss_scim_config.user_profile.enforce_password_policy | default(omit) }}"
        ldap_connection: "{{ rtss_scim_config.user_profile.ldap_connection }}"
        ldap_object_classes: "{{ rtss_scim_config.user_profile.ldap_object_classes | default(rtss_scim_user_profile_ldap_object_classes) }}"
        mappings: "{{ rtss_scim_config.user_profile.mappings }}"
        search_suffix: "{{ rtss_scim_config.user_profile.search_suffix | default(rtss_scim_config.user_profile.user_suffix) }}"
        user_dn: "{{ rtss_scim_config.user_profile.user_dn | default('uid') }}"
        user_id: "{{ rsss_scim_config.user_profile.user_id | default('uid') }}"
        user_suffix: "{{ rtss_scim_config.user_profile.user_suffix }}"
    when: rtss_scim_config.user_profile is defined
    notify:
    - Commit Changes

  always:
  - meta: flush_handlers
  tags: always
