---
# isamva/baseline/tasks/change_password.yml
# @version v2025.2.16
# @author Kevin Jeffery

- name: Change password for admin user
  ibm.isam.isam:
    action: ibmsecurity.isam.base.admin.set_pw
    isamapi:
      oldPassword: admin
      newPassword: "{{ ansible_isam_password }}"
      sessionTimeout: "{{ lmi_session_timeout }}"
  vars:
    ansible_isam_password: admin
  when: first_steps_admin_pwd | bool

- name: Reset connection
  ansible.builtin.meta: reset_connection

- name: Commit Changes and Restart LMI
  ibm.isam.isam:
    action: ibmsecurity.isam.appliance.commit_and_restart
  when: not ansible_check_mode

- name: Wait for 1 minute
  pause:
      minutes: 1
  when: not ansible_check_mode

