---
# isamva/roles/baseline/main.yml.yml
# @version v2025.2.17
# @author Kevin Jeffery

- name: Enable FIPS, Accept SLA, Complete Setup
  ansible.builtin.include_role:
    name: ibm.isam.base.first_steps
  vars:
    FIPS_cfg: "{{ isamva_fips_cfg }}"
  
- name: Check Admin Password
  ansible.builtin.uri:
    url: https://{{ ansible_host | default(inventory_hostname) }}:{{ ansible_isam_port }}/lmi
    user: "{{ ansible_isam_username }}"
    password: "{{ isamva_old_password }}"
    method: GET
    return_content: true
    force_basic_auth: true
    status_code: 200, 403
    validate_certs: false
    headers:
      Accept: application/json
  check_mode: false
  register: result

- name: Change Admin Password if necessary
  ansible.builtin.include_role:
    name: ibm.isam.base.change_admin_password
  vars:
    old_password: "{{ isamva_old_password }}"
    new_password: "{{ isamva_new_password }}"
  when:
    - result is defined
    - result.status == 200

- name: Configure Interfaces
  ansible.builtin.include_role:
    name: ibm.isam.base.configure_interfaces

- name: Set Applicance Hostname
  ansible.builtin.include_role:
    name: ibm.isam.set_network_hostname
  vars:
    set_network_hostname_hostname: "{{ host_name }}"
  when: host_name is defined

- name: DNS Configuration
  ansible.builtin.include_role:
    name: ibm.isam.base.configure_dns
  vars:
    dns: "{{ isamva_dns }}"
  when: isamva_dns is defined

- name: Time Configuration
  ansible.builtin.include_role:
    name: ibm.isam.base.configure_time
  vars:
    time_cfg: "{{ isamva_time_cfg }}"
  when: isamva_time_cfg is defined

- name: Set Host Records
  ansible.builtin.include_role:
    name: ibm.isam.base.set_host_records
  vars:
    host_records: "{{ isamva_host_records }}"
  when: isamva_host_records is defined

- meta: flush_handlers

- name: Activate Modules
  ansible.builtin.include_role:
    name: ibm.isam.base.activate_modules
  loop: "{{ isamva_activation_keys }}"
  vars:
    activation_keys:
    - "{{ key_item }}"
  loop_control:
    label: "{{ key_item.id }}"
    loop_var: key_item
  when: isamva_activation_keys is defined

- name: Update Management Certificate
  ansible.builtin.include_role:
    name: ibm.isam.base.set_management_ssl_certificate
  vars:
    update_management_ssl_cert_cert: "{{ isamva_lmi_cert_item.name }}"
    update_management_ssl_cert_pwd: "{{ isamva_lmi_cert_item.pwd }}"
  when: isamva_lmi_cert_item is defined

- meta: flush_handlers

- name: Advanced Tuning Parameters
  ansible.builtin.include_role:
    name: ibm.isam.base.configure_advanced_tuning_parameters
  vars:
    advanced_tuning_parameters: "{{ isamva_advanced_tuning_parameters }}"
    ansible_command_timeout: 120

# - name: hvdb_advanced_tuning_parameters: Advanced Tuning Parameters
#   ansible.builtin.include_role:
#     name: ibm.isam.base.configure_advanced_tuning_parameters
#   vars:
#     advanced_tuning_parameters: "{{ hvdb_advanced_tuning_parameters }}"

# - name: Config Advanced Tuning Parameters
#   ansible.builtin.include_role:
#     name: ibm.isam.base.configure_advanced_tuning_parameters
#   vars:
#     advanced_tuning_parameters: "{{ config_advanced_tuning_parameters }}"

- name: Administator Settings
  ibm.isam.isam:
    action: ibmsecurity.isam.base.admin.set
    isamapi:
      httpsPort: "{{ isamva_httpsPort | default(443) }}"
      minHeapSize: "{{ isamva_minHeapSize | int }}"
      maxHeapSize: "{{ isamva_maxHeapSize | int }}"
      acceptClientCerts: "{{ isamva_acceptClientCerts | default('false') }}"
      enabledTLS:
      - "TLSv1.2"
      enabledServerProtocols: "TLSv1.2"
      enableSSLv3: "{{ false if isam_version is version('10.0.3', 'lt') else omit }}"
      loginMessage: "{{ isamva_loginMessage }}"
      loginHeader: "{{ isamva_environment | default('') }} {{ description | default(host_name) }}"
      pendingChangesLifetime: "{{ isamva_pendingChangesLifetime | default(24) }}"
  notify: Commit Changes and Restart

- meta: flush_handlers

# - name: Import Signer Certificates
#   include_role:
#     name: isam_config/import_signer_certificates
#   vars:
#     kdb_item:
#       name: "rt_profile_keys"
#       kdb: "rt_profile_keys.kdb"
#     signer_certificates: "{{ isamva_signer_certificates }}"
#     expired_certificates:
#       - label: "CN=*.ice.ibmcloud.com,O=International Business Machines Corporation,L=Armonk,ST=New York,C=US"

# - meta: flush_handlers

# - name: Configure System Alert Forwarding
#   include_role:
#     name: isam_config/system_alerts
#   when: isamva_system_alerts is defined
