---
# /roles/config_junctions/tasks/add_servers.yml
# @version v2025.3.31.0
# @author Kevin Jeffery

- name: Add Additional Servers - {{ junction_item.name }}
  ibm.isam.isam:
    action: ibmsecurity.isam.web.reverse_proxy.junctions_server.add
    isamapi:
      reverseproxy_id:        "{{ isamva_proxy_name }}"
      junction_point:         "{{ junction_item.name }}"
      junction_type:          "{{ junction_item.junction_type }}"
      server_hostname:        "{{ item.server_hostname }}"
      server_port:            "{{ item.server_port }}"
      server_dn:              "{{ item.server_dn | default(omit) }}"
      server_uuid:            "{{ (item.server_hostname + ':' + item.server_port) | to_uuid }}"
      virtual_hostname:       "{{ item.virtual_hostname | default(omit) }}"
      query_contents:         "{{ junction_item.query_contents | default(omit) }}"
      case_sensitive_url:     "{{ junction_item.case_sensitive_url | default(item.caseins) | default(omit) }}"
      windows_style_url:      "{{ junction_item.windows_style_url | default(item.windows_style_url) | default(omit) }}"
      https_port:             "{{ junction_item.https_port | default(omit) }}"
      http_port:              "{{ junction_item.http_port | default(omit) }}"
      proxy_hostname:         "{{ junction_item.proxy_hostname | default(omit) }}"
      proxy_port:             "{{ junction_item.proxy_port | default(omit) }}"
      sms_environment:        "{{ junction_item.sms_environment | default(omit) }}"
      vhost_label:            "{{ junction_item.vhost_label | default(omit) }}"
  # failed_when:
  #   - ret_server_add.rc > 0
  #   - "'DPWWA1222E' not in ret_server_add.message"
  ignore_errors: true
  loop: "{{ junction_item.servers }}"
  loop_control:
    label: "{{ junction_item.name }}:{{ item.server_hostname }}:{{ item.port }}"
  register: ret_server_add
  vars:
    ansible_command_timeout: 120
  tags: always
