---
# roles/proxy_configuration_stanza/tasks/main.yml
# @version v2025.3.23.0
# @author Kevin Jeffery

- name: Reverse Proxy Configuration
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: "ibmsecurity.isam.web.reverse_proxy.configuration.entry.{{ item.action | default('set') }}"
    isamapi:
      reverseproxy_id: "{{ isamva_proxy_item.inst_name }}"
      stanza_id: "{{ isamva_proxy_item.stanza }}"
      entries: "{{ item.entries }}"
  loop: "{{ isamva_stanza_item.proxy_conf }}"
  loop_control:
    label: "{{ isamva_proxy_item.stanza }}"
  notify:
  - Commit Changes
  when:
  - isamva_stanza_item.proxy_conf is defined
  - item.entries is defined
  tags: always
