---
# middkeware/roles/db2/vars/main.yml
# @version v1.08_2025-MAR-20
# @author Kevin Jeffery

db2_packages:
  - unzip
  - pam
  - pam.i686
  - ksh
  - binutils
  - rsync

gskit_home: /usr/local/ibm/gsk8
gskit64_home: /usr/local/ibm/gsk8_64
