---
# middleware/roles/gskit/tasks/main.yml
# @version v2025.3.9.0
# @author Kevin Jeffery

- name: Determine Installed Version
  autom8.middleware.gsk8version:
    platform: "{{ gskit_platform }}"
    version: "{{ gskit_version }}"
  register: ret_gsk8version
  tags: always

- name: GSKit Info
  debug:
    var: ret_gsk8version.data
  tags: always

- name: Decompressing GSKit Package
  ansible.builtin.unarchive:
    creates: "{{ gskit_source_dir }}/{{ ret_gsk8version.data.name }}"
    dest: "{{ gskit_source_dir }}"
    owner: "{{ gskit_owner | default(ansible_user) }}"
    remote_src: yes
    src: "{{ gskit_source_dir }}/{{ ret_gsk8version.data.archive }}"
  become: true
  tags: always

- name: Install packages
  package:
    name: "{{ gskit_source_dir }}/{{ ret_gsk8version.data.name }}/{{ item }}"
  loop: "{{ ret_gsk8version.data.packages }}"
  loop_control:
    label: "{{ item }}"
  become: true
  when: not ret_gsk8version.data.installed or ret_gsk8version.data.upgrade
  tags: always
