---
# middleware/roles/gskit/meta/main.yml
# @version v2025.2.13.0
# @author Kevin Jeffery
galaxy_info:
  author: Kevin Jeffery
  description: Role to install IBM Global Security Kit
  company: MicroKnight
  license: Apache
  min_ansible_version: 2.2
